// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: sakissh.proto

package sakissh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SakiSSH_Execute_FullMethodName            = "/sakissh.SakiSSH/Execute"
	SakiSSH_ExecuteStream_FullMethodName      = "/sakissh.SakiSSH/ExecuteStream"
	SakiSSH_Cancel_FullMethodName             = "/sakissh.SakiSSH/Cancel"
	SakiSSH_Signal_FullMethodName             = "/sakissh.SakiSSH/Signal"
	SakiSSH_Ping_FullMethodName               = "/sakissh.SakiSSH/Ping"
	SakiSSH_FileUpload_FullMethodName         = "/sakissh.SakiSSH/FileUpload"
	SakiSSH_FileDownload_FullMethodName       = "/sakissh.SakiSSH/FileDownload"
	SakiSSH_Authenticate_FullMethodName       = "/sakissh.SakiSSH/Authenticate"
	SakiSSH_CognitiveChallenge_FullMethodName = "/sakissh.SakiSSH/CognitiveChallenge"
	SakiSSH_SecurityStatus_FullMethodName     = "/sakissh.SakiSSH/SecurityStatus"
	SakiSSH_RawFileTransfer_FullMethodName    = "/sakissh.SakiSSH/RawFileTransfer"
	SakiSSH_RenewSession_FullMethodName       = "/sakissh.SakiSSH/RenewSession"
)

// SakiSSHClient is the client API for SakiSSH service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SakiSSHClient interface {
	// 執行指令並返回單次結果 (用於快速指令)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// 流式執行指令 (用於需要實時輸出或互動的場景)
	ExecuteStream(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	// 取消執行中的進程 (無 timeout，取消即殺)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// 對執行中的進程發送 POSIX 信號
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	// 連線狀態自檢 (Client 單向 request)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// 檔案上傳 (Client → Daemon 串流)
	FileUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, FileTransferResponse], error)
	// 檔案下載 (Daemon → Client 串流)
	FileDownload(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// v6: 認證握手 (Ed25519 + ChaCha20-Poly1305 挑戰)
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// v6: 認知挑戰 (ChaCha20 解密驗證)
	CognitiveChallenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error)
	// v6: 安全狀態查詢 (tarpit / session / blocked IP 統計)
	SecurityStatus(ctx context.Context, in *SecurityStatusRequest, opts ...grpc.CallOption) (*SecurityStatusResponse, error)
	// v6: Raw File Transfer（直接 FD 寫入，繞過 shell I/O，bit-perfect）
	RawFileTransfer(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RawFileChunk, RawFileTransferResponse], error)
	// v6: Session 續期（延長 expires_at，daemon 決定時長）
	RenewSession(ctx context.Context, in *RenewSessionRequest, opts ...grpc.CallOption) (*RenewSessionResponse, error)
}

type sakiSSHClient struct {
	cc grpc.ClientConnInterface
}

func NewSakiSSHClient(cc grpc.ClientConnInterface) SakiSSHClient {
	return &sakiSSHClient{cc}
}

func (c *sakiSSHClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, SakiSSH_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) ExecuteStream(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SakiSSH_ServiceDesc.Streams[0], SakiSSH_ExecuteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SakiSSH_ExecuteStreamClient = grpc.ServerStreamingClient[StreamResponse]

func (c *sakiSSHClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, SakiSSH_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, SakiSSH_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, SakiSSH_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) FileUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, FileTransferResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SakiSSH_ServiceDesc.Streams[1], SakiSSH_FileUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, FileTransferResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SakiSSH_FileUploadClient = grpc.ClientStreamingClient[FileChunk, FileTransferResponse]

func (c *sakiSSHClient) FileDownload(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SakiSSH_ServiceDesc.Streams[2], SakiSSH_FileDownload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileDownloadRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SakiSSH_FileDownloadClient = grpc.ServerStreamingClient[FileChunk]

func (c *sakiSSHClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, SakiSSH_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) CognitiveChallenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChallengeResponse)
	err := c.cc.Invoke(ctx, SakiSSH_CognitiveChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) SecurityStatus(ctx context.Context, in *SecurityStatusRequest, opts ...grpc.CallOption) (*SecurityStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityStatusResponse)
	err := c.cc.Invoke(ctx, SakiSSH_SecurityStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) RawFileTransfer(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RawFileChunk, RawFileTransferResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SakiSSH_ServiceDesc.Streams[3], SakiSSH_RawFileTransfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RawFileChunk, RawFileTransferResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SakiSSH_RawFileTransferClient = grpc.ClientStreamingClient[RawFileChunk, RawFileTransferResponse]

func (c *sakiSSHClient) RenewSession(ctx context.Context, in *RenewSessionRequest, opts ...grpc.CallOption) (*RenewSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewSessionResponse)
	err := c.cc.Invoke(ctx, SakiSSH_RenewSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SakiSSHServer is the server API for SakiSSH service.
// All implementations must embed UnimplementedSakiSSHServer
// for forward compatibility.
type SakiSSHServer interface {
	// 執行指令並返回單次結果 (用於快速指令)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// 流式執行指令 (用於需要實時輸出或互動的場景)
	ExecuteStream(*ExecuteRequest, grpc.ServerStreamingServer[StreamResponse]) error
	// 取消執行中的進程 (無 timeout，取消即殺)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	// 對執行中的進程發送 POSIX 信號
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	// 連線狀態自檢 (Client 單向 request)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// 檔案上傳 (Client → Daemon 串流)
	FileUpload(grpc.ClientStreamingServer[FileChunk, FileTransferResponse]) error
	// 檔案下載 (Daemon → Client 串流)
	FileDownload(*FileDownloadRequest, grpc.ServerStreamingServer[FileChunk]) error
	// v6: 認證握手 (Ed25519 + ChaCha20-Poly1305 挑戰)
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	// v6: 認知挑戰 (ChaCha20 解密驗證)
	CognitiveChallenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error)
	// v6: 安全狀態查詢 (tarpit / session / blocked IP 統計)
	SecurityStatus(context.Context, *SecurityStatusRequest) (*SecurityStatusResponse, error)
	// v6: Raw File Transfer（直接 FD 寫入，繞過 shell I/O，bit-perfect）
	RawFileTransfer(grpc.ClientStreamingServer[RawFileChunk, RawFileTransferResponse]) error
	// v6: Session 續期（延長 expires_at，daemon 決定時長）
	RenewSession(context.Context, *RenewSessionRequest) (*RenewSessionResponse, error)
	mustEmbedUnimplementedSakiSSHServer()
}

// UnimplementedSakiSSHServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSakiSSHServer struct{}

func (UnimplementedSakiSSHServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedSakiSSHServer) ExecuteStream(*ExecuteRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteStream not implemented")
}
func (UnimplementedSakiSSHServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedSakiSSHServer) Signal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedSakiSSHServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSakiSSHServer) FileUpload(grpc.ClientStreamingServer[FileChunk, FileTransferResponse]) error {
	return status.Error(codes.Unimplemented, "method FileUpload not implemented")
}
func (UnimplementedSakiSSHServer) FileDownload(*FileDownloadRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method FileDownload not implemented")
}
func (UnimplementedSakiSSHServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedSakiSSHServer) CognitiveChallenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CognitiveChallenge not implemented")
}
func (UnimplementedSakiSSHServer) SecurityStatus(context.Context, *SecurityStatusRequest) (*SecurityStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SecurityStatus not implemented")
}
func (UnimplementedSakiSSHServer) RawFileTransfer(grpc.ClientStreamingServer[RawFileChunk, RawFileTransferResponse]) error {
	return status.Error(codes.Unimplemented, "method RawFileTransfer not implemented")
}
func (UnimplementedSakiSSHServer) RenewSession(context.Context, *RenewSessionRequest) (*RenewSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewSession not implemented")
}
func (UnimplementedSakiSSHServer) mustEmbedUnimplementedSakiSSHServer() {}
func (UnimplementedSakiSSHServer) testEmbeddedByValue()                 {}

// UnsafeSakiSSHServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SakiSSHServer will
// result in compilation errors.
type UnsafeSakiSSHServer interface {
	mustEmbedUnimplementedSakiSSHServer()
}

func RegisterSakiSSHServer(s grpc.ServiceRegistrar, srv SakiSSHServer) {
	// If the following call panics, it indicates UnimplementedSakiSSHServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SakiSSH_ServiceDesc, srv)
}

func _SakiSSH_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SakiSSH_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_ExecuteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SakiSSHServer).ExecuteStream(m, &grpc.GenericServerStream[ExecuteRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SakiSSH_ExecuteStreamServer = grpc.ServerStreamingServer[StreamResponse]

func _SakiSSH_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SakiSSH_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SakiSSH_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).Signal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SakiSSH_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_FileUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SakiSSHServer).FileUpload(&grpc.GenericServerStream[FileChunk, FileTransferResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SakiSSH_FileUploadServer = grpc.ClientStreamingServer[FileChunk, FileTransferResponse]

func _SakiSSH_FileDownload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SakiSSHServer).FileDownload(m, &grpc.GenericServerStream[FileDownloadRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SakiSSH_FileDownloadServer = grpc.ServerStreamingServer[FileChunk]

func _SakiSSH_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SakiSSH_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_CognitiveChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).CognitiveChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SakiSSH_CognitiveChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).CognitiveChallenge(ctx, req.(*ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_SecurityStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).SecurityStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SakiSSH_SecurityStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).SecurityStatus(ctx, req.(*SecurityStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_RawFileTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SakiSSHServer).RawFileTransfer(&grpc.GenericServerStream[RawFileChunk, RawFileTransferResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SakiSSH_RawFileTransferServer = grpc.ClientStreamingServer[RawFileChunk, RawFileTransferResponse]

func _SakiSSH_RenewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).RenewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SakiSSH_RenewSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).RenewSession(ctx, req.(*RenewSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SakiSSH_ServiceDesc is the grpc.ServiceDesc for SakiSSH service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SakiSSH_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sakissh.SakiSSH",
	HandlerType: (*SakiSSHServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _SakiSSH_Execute_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _SakiSSH_Cancel_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _SakiSSH_Signal_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _SakiSSH_Ping_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _SakiSSH_Authenticate_Handler,
		},
		{
			MethodName: "CognitiveChallenge",
			Handler:    _SakiSSH_CognitiveChallenge_Handler,
		},
		{
			MethodName: "SecurityStatus",
			Handler:    _SakiSSH_SecurityStatus_Handler,
		},
		{
			MethodName: "RenewSession",
			Handler:    _SakiSSH_RenewSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteStream",
			Handler:       _SakiSSH_ExecuteStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileUpload",
			Handler:       _SakiSSH_FileUpload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FileDownload",
			Handler:       _SakiSSH_FileDownload_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RawFileTransfer",
			Handler:       _SakiSSH_RawFileTransfer_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sakissh.proto",
}
