// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sakissh.proto

package sakissh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// POSIX 信號映射
type PosixSignal int32

const (
	PosixSignal_SIGINT  PosixSignal = 0 // Ctrl+C (Windows: CTRL_C_EVENT)
	PosixSignal_SIGTERM PosixSignal = 1 // 正常終止 (Windows: TerminateProcess)
	PosixSignal_SIGKILL PosixSignal = 2 // 強制終止 (Windows: TerminateProcess)
	PosixSignal_SIGHUP  PosixSignal = 3 // 掛起 (Windows: 忽略或終止)
)

// Enum value maps for PosixSignal.
var (
	PosixSignal_name = map[int32]string{
		0: "SIGINT",
		1: "SIGTERM",
		2: "SIGKILL",
		3: "SIGHUP",
	}
	PosixSignal_value = map[string]int32{
		"SIGINT":  0,
		"SIGTERM": 1,
		"SIGKILL": 2,
		"SIGHUP":  3,
	}
)

func (x PosixSignal) Enum() *PosixSignal {
	p := new(PosixSignal)
	*p = x
	return p
}

func (x PosixSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PosixSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_sakissh_proto_enumTypes[0].Descriptor()
}

func (PosixSignal) Type() protoreflect.EnumType {
	return &file_sakissh_proto_enumTypes[0]
}

func (x PosixSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PosixSignal.Descriptor instead.
func (PosixSignal) EnumDescriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{0}
}

type StreamResponse_Source int32

const (
	StreamResponse_STDOUT StreamResponse_Source = 0
	StreamResponse_STDERR StreamResponse_Source = 1
	// v6: 系統訊息（排隊通知、認證事件等）
	StreamResponse_SYSTEM StreamResponse_Source = 2
)

// Enum value maps for StreamResponse_Source.
var (
	StreamResponse_Source_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "SYSTEM",
	}
	StreamResponse_Source_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"SYSTEM": 2,
	}
)

func (x StreamResponse_Source) Enum() *StreamResponse_Source {
	p := new(StreamResponse_Source)
	*p = x
	return p
}

func (x StreamResponse_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamResponse_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_sakissh_proto_enumTypes[1].Descriptor()
}

func (StreamResponse_Source) Type() protoreflect.EnumType {
	return &file_sakissh_proto_enumTypes[1]
}

func (x StreamResponse_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamResponse_Source.Descriptor instead.
func (StreamResponse_Source) EnumDescriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{2, 0}
}

type ExecuteRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Command string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Cwd     string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env     map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 執行 ID，用於 Cancel/Signal 定位。Client 端生成 (UUID)。
	ExecutionId string `protobuf:"bytes,5,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// v6: Session 綁定（認證後取得的 session_id）
	SessionId string `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// v6: 斷線重連旗標
	IsReattach bool `protobuf:"varint,7,opt,name=is_reattach,json=isReattach,proto3" json:"is_reattach,omitempty"`
	// v6: 從此 offset 開始續傳 PTY 輸出
	ResumeOffset  uint64 `protobuf:"varint,8,opt,name=resume_offset,json=resumeOffset,proto3" json:"resume_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_sakissh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteRequest) GetIsReattach() bool {
	if x != nil {
		return x.IsReattach
	}
	return false
}

func (x *ExecuteRequest) GetResumeOffset() uint64 {
	if x != nil {
		return x.ResumeOffset
	}
	return 0
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_sakissh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecuteResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecuteResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type StreamResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Source   StreamResponse_Source  `protobuf:"varint,1,opt,name=source,proto3,enum=sakissh.StreamResponse_Source" json:"source,omitempty"`
	Data     []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ExitCode *int32                 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	// v6: 指令是否進入排隊等待
	IsQueued bool `protobuf:"varint,4,opt,name=is_queued,json=isQueued,proto3" json:"is_queued,omitempty"`
	// v6: 排隊位置（0 = 未排隊）
	QueuePosition int32 `protobuf:"varint,5,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	// v6: PTY Ring Buffer 斷點續傳用 offset
	Offset        uint64 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_sakissh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{2}
}

func (x *StreamResponse) GetSource() StreamResponse_Source {
	if x != nil {
		return x.Source
	}
	return StreamResponse_STDOUT
}

func (x *StreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamResponse) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *StreamResponse) GetIsQueued() bool {
	if x != nil {
		return x.IsQueued
	}
	return false
}

func (x *StreamResponse) GetQueuePosition() int32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *StreamResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_sakissh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{3}
}

func (x *CancelRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_sakissh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{4}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Signal        PosixSignal            `protobuf:"varint,2,opt,name=signal,proto3,enum=sakissh.PosixSignal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_sakissh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{5}
}

func (x *SignalRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SignalRequest) GetSignal() PosixSignal {
	if x != nil {
		return x.Signal
	}
	return PosixSignal_SIGINT
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_sakissh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{6}
}

func (x *SignalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_sakissh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{7}
}

type PingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DaemonVersion   string                 `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	UptimeSeconds   uint64                 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ShellType       string                 `protobuf:"bytes,3,opt,name=shell_type,json=shellType,proto3" json:"shell_type,omitempty"`
	ShellPath       string                 `protobuf:"bytes,4,opt,name=shell_path,json=shellPath,proto3" json:"shell_path,omitempty"`
	Os              string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	ActiveProcesses uint32                 `protobuf:"varint,6,opt,name=active_processes,json=activeProcesses,proto3" json:"active_processes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_sakissh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{8}
}

func (x *PingResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *PingResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *PingResponse) GetShellType() string {
	if x != nil {
		return x.ShellType
	}
	return ""
}

func (x *PingResponse) GetShellPath() string {
	if x != nil {
		return x.ShellPath
	}
	return ""
}

func (x *PingResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *PingResponse) GetActiveProcesses() uint32 {
	if x != nil {
		return x.ActiveProcesses
	}
	return 0
}

type FileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 首個 chunk 必須包含 metadata
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*FileChunk_Metadata
	//	*FileChunk_Data
	Payload       isFileChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_sakissh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{9}
}

func (x *FileChunk) GetPayload() isFileChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FileChunk) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*FileChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*FileChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isFileChunk_Payload interface {
	isFileChunk_Payload()
}

type FileChunk_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type FileChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*FileChunk_Metadata) isFileChunk_Payload() {}

func (*FileChunk_Data) isFileChunk_Payload() {}

type FileMetadata struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RemotePath string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	TotalSize  uint64                 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// 斷點續傳：從此 offset 開始寫入
	Offset        uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_sakissh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{10}
}

func (x *FileMetadata) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *FileMetadata) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileMetadata) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FileTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BytesWritten  uint64                 `protobuf:"varint,3,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferResponse) Reset() {
	*x = FileTransferResponse{}
	mi := &file_sakissh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferResponse) ProtoMessage() {}

func (x *FileTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferResponse.ProtoReflect.Descriptor instead.
func (*FileTransferResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{11}
}

func (x *FileTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileTransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileTransferResponse) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type FileDownloadRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RemotePath string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	// 斷點續傳：從此 offset 開始讀取
	Offset        uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadRequest) Reset() {
	*x = FileDownloadRequest{}
	mi := &file_sakissh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadRequest) ProtoMessage() {}

func (x *FileDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadRequest) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{12}
}

func (x *FileDownloadRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *FileDownloadRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_sakissh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{13}
}

func (x *AuthRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AuthRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *AuthRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuthRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type AuthResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Success                   bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId                 string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CapabilityHash            string                 `protobuf:"bytes,3,opt,name=capability_hash,json=capabilityHash,proto3" json:"capability_hash,omitempty"`
	ChachaChallengeNonce      []byte                 `protobuf:"bytes,4,opt,name=chacha_challenge_nonce,json=chachaChallengeNonce,proto3" json:"chacha_challenge_nonce,omitempty"`
	ChachaChallengeCiphertext []byte                 `protobuf:"bytes,5,opt,name=chacha_challenge_ciphertext,json=chachaChallengeCiphertext,proto3" json:"chacha_challenge_ciphertext,omitempty"`
	Message                   string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_sakissh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{14}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthResponse) GetCapabilityHash() string {
	if x != nil {
		return x.CapabilityHash
	}
	return ""
}

func (x *AuthResponse) GetChachaChallengeNonce() []byte {
	if x != nil {
		return x.ChachaChallengeNonce
	}
	return nil
}

func (x *AuthResponse) GetChachaChallengeCiphertext() []byte {
	if x != nil {
		return x.ChachaChallengeCiphertext
	}
	return nil
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChallengeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DecryptedPlaintext []byte                 `protobuf:"bytes,1,opt,name=decrypted_plaintext,json=decryptedPlaintext,proto3" json:"decrypted_plaintext,omitempty"`
	ClientEkmHmac      []byte                 `protobuf:"bytes,2,opt,name=client_ekm_hmac,json=clientEkmHmac,proto3" json:"client_ekm_hmac,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_sakissh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{15}
}

func (x *ChallengeRequest) GetDecryptedPlaintext() []byte {
	if x != nil {
		return x.DecryptedPlaintext
	}
	return nil
}

func (x *ChallengeRequest) GetClientEkmHmac() []byte {
	if x != nil {
		return x.ClientEkmHmac
	}
	return nil
}

type ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_sakissh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{16}
}

func (x *ChallengeResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ChallengeResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *ChallengeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SecurityStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityStatusRequest) Reset() {
	*x = SecurityStatusRequest{}
	mi := &file_sakissh_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityStatusRequest) ProtoMessage() {}

func (x *SecurityStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityStatusRequest.ProtoReflect.Descriptor instead.
func (*SecurityStatusRequest) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{17}
}

type SecurityStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveTarpits  uint32                 `protobuf:"varint,1,opt,name=active_tarpits,json=activeTarpits,proto3" json:"active_tarpits,omitempty"`
	ActiveSessions uint32                 `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	BlockedIps     uint32                 `protobuf:"varint,3,opt,name=blocked_ips,json=blockedIps,proto3" json:"blocked_ips,omitempty"`
	PolicyVersion  string                 `protobuf:"bytes,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SecurityStatusResponse) Reset() {
	*x = SecurityStatusResponse{}
	mi := &file_sakissh_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityStatusResponse) ProtoMessage() {}

func (x *SecurityStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityStatusResponse.ProtoReflect.Descriptor instead.
func (*SecurityStatusResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{18}
}

func (x *SecurityStatusResponse) GetActiveTarpits() uint32 {
	if x != nil {
		return x.ActiveTarpits
	}
	return 0
}

func (x *SecurityStatusResponse) GetActiveSessions() uint32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *SecurityStatusResponse) GetBlockedIps() uint32 {
	if x != nil {
		return x.BlockedIps
	}
	return 0
}

func (x *SecurityStatusResponse) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

type RawFileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RawFileChunk_Metadata
	//	*RawFileChunk_Data
	Payload       isRawFileChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawFileChunk) Reset() {
	*x = RawFileChunk{}
	mi := &file_sakissh_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawFileChunk) ProtoMessage() {}

func (x *RawFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawFileChunk.ProtoReflect.Descriptor instead.
func (*RawFileChunk) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{19}
}

func (x *RawFileChunk) GetPayload() isRawFileChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RawFileChunk) GetMetadata() *RawFileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*RawFileChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *RawFileChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*RawFileChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isRawFileChunk_Payload interface {
	isRawFileChunk_Payload()
}

type RawFileChunk_Metadata struct {
	Metadata *RawFileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type RawFileChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*RawFileChunk_Metadata) isRawFileChunk_Payload() {}

func (*RawFileChunk_Data) isRawFileChunk_Payload() {}

type RawFileMetadata struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RemotePath string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	TotalSize  uint64                 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// 斷點續傳：從此 offset 開始寫入
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// 完整性驗證（SHA-256 hex）
	ChecksumSha256 string `protobuf:"bytes,4,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RawFileMetadata) Reset() {
	*x = RawFileMetadata{}
	mi := &file_sakissh_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawFileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawFileMetadata) ProtoMessage() {}

func (x *RawFileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawFileMetadata.ProtoReflect.Descriptor instead.
func (*RawFileMetadata) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{20}
}

func (x *RawFileMetadata) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *RawFileMetadata) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *RawFileMetadata) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RawFileMetadata) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

type RawFileTransferResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message      string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BytesWritten uint64                 `protobuf:"varint,3,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	// 寫入後校驗（SHA-256 hex）
	ChecksumSha256 string `protobuf:"bytes,4,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RawFileTransferResponse) Reset() {
	*x = RawFileTransferResponse{}
	mi := &file_sakissh_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawFileTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawFileTransferResponse) ProtoMessage() {}

func (x *RawFileTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawFileTransferResponse.ProtoReflect.Descriptor instead.
func (*RawFileTransferResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{21}
}

func (x *RawFileTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RawFileTransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RawFileTransferResponse) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *RawFileTransferResponse) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

type RenewSessionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Client hint: 請求的續期秒數。Daemon MAY honor, cap, or ignore。
	// 若為 0 或未設定，daemon SHOULD 使用預設續期時長。
	RequestedExtensionSeconds uint32 `protobuf:"varint,2,opt,name=requested_extension_seconds,json=requestedExtensionSeconds,proto3" json:"requested_extension_seconds,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RenewSessionRequest) Reset() {
	*x = RenewSessionRequest{}
	mi := &file_sakissh_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewSessionRequest) ProtoMessage() {}

func (x *RenewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewSessionRequest.ProtoReflect.Descriptor instead.
func (*RenewSessionRequest) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{22}
}

func (x *RenewSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RenewSessionRequest) GetRequestedExtensionSeconds() uint32 {
	if x != nil {
		return x.RequestedExtensionSeconds
	}
	return 0
}

type RenewSessionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 新的過期時間（RFC 3339 timestamp）
	NewExpiresAt string `protobuf:"bytes,2,opt,name=new_expires_at,json=newExpiresAt,proto3" json:"new_expires_at,omitempty"`
	Message      string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// 實際授予的續期秒數（daemon 最終裁決）
	GrantedExtensionSeconds uint32 `protobuf:"varint,4,opt,name=granted_extension_seconds,json=grantedExtensionSeconds,proto3" json:"granted_extension_seconds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RenewSessionResponse) Reset() {
	*x = RenewSessionResponse{}
	mi := &file_sakissh_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewSessionResponse) ProtoMessage() {}

func (x *RenewSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sakissh_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewSessionResponse.ProtoReflect.Descriptor instead.
func (*RenewSessionResponse) Descriptor() ([]byte, []int) {
	return file_sakissh_proto_rawDescGZIP(), []int{23}
}

func (x *RenewSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenewSessionResponse) GetNewExpiresAt() string {
	if x != nil {
		return x.NewExpiresAt
	}
	return ""
}

func (x *RenewSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RenewSessionResponse) GetGrantedExtensionSeconds() uint32 {
	if x != nil {
		return x.GrantedExtensionSeconds
	}
	return 0
}

var File_sakissh_proto protoreflect.FileDescriptor

const file_sakissh_proto_rawDesc = "" +
	"\n" +
	"\rsakissh.proto\x12\asakissh\"\xc4\x02\n" +
	"\x0eExecuteRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x122\n" +
	"\x03env\x18\x04 \x03(\v2 .sakissh.ExecuteRequest.EnvEntryR\x03env\x12!\n" +
	"\fexecution_id\x18\x05 \x01(\tR\vexecutionId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vis_reattach\x18\a \x01(\bR\n" +
	"isReattach\x12#\n" +
	"\rresume_offset\x18\b \x01(\x04R\fresumeOffset\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x0fExecuteResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\"\x96\x02\n" +
	"\x0eStreamResponse\x126\n" +
	"\x06source\x18\x01 \x01(\x0e2\x1e.sakissh.StreamResponse.SourceR\x06source\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12 \n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12\x1b\n" +
	"\tis_queued\x18\x04 \x01(\bR\bisQueued\x12%\n" +
	"\x0equeue_position\x18\x05 \x01(\x05R\rqueuePosition\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x04R\x06offset\",\n" +
	"\x06Source\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x02B\f\n" +
	"\n" +
	"_exit_code\"2\n" +
	"\rCancelRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"D\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\rSignalRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12,\n" +
	"\x06signal\x18\x02 \x01(\x0e2\x14.sakissh.PosixSignalR\x06signal\"D\n" +
	"\x0eSignalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vPingRequest\"\xd5\x01\n" +
	"\fPingResponse\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x04R\ruptimeSeconds\x12\x1d\n" +
	"\n" +
	"shell_type\x18\x03 \x01(\tR\tshellType\x12\x1d\n" +
	"\n" +
	"shell_path\x18\x04 \x01(\tR\tshellPath\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12)\n" +
	"\x10active_processes\x18\x06 \x01(\rR\x0factiveProcesses\"a\n" +
	"\tFileChunk\x123\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.sakissh.FileMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"f\n" +
	"\fFileMetadata\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"o\n" +
	"\x14FileTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rbytes_written\x18\x03 \x01(\x04R\fbytesWritten\"N\n" +
	"\x13FileDownloadRequest\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"\x7f\n" +
	"\vAuthRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\"\x80\x02\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12'\n" +
	"\x0fcapability_hash\x18\x03 \x01(\tR\x0ecapabilityHash\x124\n" +
	"\x16chacha_challenge_nonce\x18\x04 \x01(\fR\x14chachaChallengeNonce\x12>\n" +
	"\x1bchacha_challenge_ciphertext\x18\x05 \x01(\fR\x19chachaChallengeCiphertext\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"k\n" +
	"\x10ChallengeRequest\x12/\n" +
	"\x13decrypted_plaintext\x18\x01 \x01(\fR\x12decryptedPlaintext\x12&\n" +
	"\x0fclient_ekm_hmac\x18\x02 \x01(\fR\rclientEkmHmac\"j\n" +
	"\x11ChallengeResponse\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x17\n" +
	"\x15SecurityStatusRequest\"\xb0\x01\n" +
	"\x16SecurityStatusResponse\x12%\n" +
	"\x0eactive_tarpits\x18\x01 \x01(\rR\ractiveTarpits\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\rR\x0eactiveSessions\x12\x1f\n" +
	"\vblocked_ips\x18\x03 \x01(\rR\n" +
	"blockedIps\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\tR\rpolicyVersion\"g\n" +
	"\fRawFileChunk\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.sakissh.RawFileMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\x92\x01\n" +
	"\x0fRawFileMetadata\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12'\n" +
	"\x0fchecksum_sha256\x18\x04 \x01(\tR\x0echecksumSha256\"\x9b\x01\n" +
	"\x17RawFileTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rbytes_written\x18\x03 \x01(\x04R\fbytesWritten\x12'\n" +
	"\x0fchecksum_sha256\x18\x04 \x01(\tR\x0echecksumSha256\"t\n" +
	"\x13RenewSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\x1brequested_extension_seconds\x18\x02 \x01(\rR\x19requestedExtensionSeconds\"\xac\x01\n" +
	"\x14RenewSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\x0enew_expires_at\x18\x02 \x01(\tR\fnewExpiresAt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12:\n" +
	"\x19granted_extension_seconds\x18\x04 \x01(\rR\x17grantedExtensionSeconds*?\n" +
	"\vPosixSignal\x12\n" +
	"\n" +
	"\x06SIGINT\x10\x00\x12\v\n" +
	"\aSIGTERM\x10\x01\x12\v\n" +
	"\aSIGKILL\x10\x02\x12\n" +
	"\n" +
	"\x06SIGHUP\x10\x032\xb6\x06\n" +
	"\aSakiSSH\x12<\n" +
	"\aExecute\x12\x17.sakissh.ExecuteRequest\x1a\x18.sakissh.ExecuteResponse\x12C\n" +
	"\rExecuteStream\x12\x17.sakissh.ExecuteRequest\x1a\x17.sakissh.StreamResponse0\x01\x129\n" +
	"\x06Cancel\x12\x16.sakissh.CancelRequest\x1a\x17.sakissh.CancelResponse\x129\n" +
	"\x06Signal\x12\x16.sakissh.SignalRequest\x1a\x17.sakissh.SignalResponse\x123\n" +
	"\x04Ping\x12\x14.sakissh.PingRequest\x1a\x15.sakissh.PingResponse\x12A\n" +
	"\n" +
	"FileUpload\x12\x12.sakissh.FileChunk\x1a\x1d.sakissh.FileTransferResponse(\x01\x12B\n" +
	"\fFileDownload\x12\x1c.sakissh.FileDownloadRequest\x1a\x12.sakissh.FileChunk0\x01\x12;\n" +
	"\fAuthenticate\x12\x14.sakissh.AuthRequest\x1a\x15.sakissh.AuthResponse\x12K\n" +
	"\x12CognitiveChallenge\x12\x19.sakissh.ChallengeRequest\x1a\x1a.sakissh.ChallengeResponse\x12Q\n" +
	"\x0eSecurityStatus\x12\x1e.sakissh.SecurityStatusRequest\x1a\x1f.sakissh.SecurityStatusResponse\x12L\n" +
	"\x0fRawFileTransfer\x12\x15.sakissh.RawFileChunk\x1a .sakissh.RawFileTransferResponse(\x01\x12K\n" +
	"\fRenewSession\x12\x1c.sakissh.RenewSessionRequest\x1a\x1d.sakissh.RenewSessionResponseB0Z.github.com/sakistudio/sakissh-go/proto/sakisshb\x06proto3"

var (
	file_sakissh_proto_rawDescOnce sync.Once
	file_sakissh_proto_rawDescData []byte
)

func file_sakissh_proto_rawDescGZIP() []byte {
	file_sakissh_proto_rawDescOnce.Do(func() {
		file_sakissh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sakissh_proto_rawDesc), len(file_sakissh_proto_rawDesc)))
	})
	return file_sakissh_proto_rawDescData
}

var file_sakissh_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sakissh_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_sakissh_proto_goTypes = []any{
	(PosixSignal)(0),                // 0: sakissh.PosixSignal
	(StreamResponse_Source)(0),      // 1: sakissh.StreamResponse.Source
	(*ExecuteRequest)(nil),          // 2: sakissh.ExecuteRequest
	(*ExecuteResponse)(nil),         // 3: sakissh.ExecuteResponse
	(*StreamResponse)(nil),          // 4: sakissh.StreamResponse
	(*CancelRequest)(nil),           // 5: sakissh.CancelRequest
	(*CancelResponse)(nil),          // 6: sakissh.CancelResponse
	(*SignalRequest)(nil),           // 7: sakissh.SignalRequest
	(*SignalResponse)(nil),          // 8: sakissh.SignalResponse
	(*PingRequest)(nil),             // 9: sakissh.PingRequest
	(*PingResponse)(nil),            // 10: sakissh.PingResponse
	(*FileChunk)(nil),               // 11: sakissh.FileChunk
	(*FileMetadata)(nil),            // 12: sakissh.FileMetadata
	(*FileTransferResponse)(nil),    // 13: sakissh.FileTransferResponse
	(*FileDownloadRequest)(nil),     // 14: sakissh.FileDownloadRequest
	(*AuthRequest)(nil),             // 15: sakissh.AuthRequest
	(*AuthResponse)(nil),            // 16: sakissh.AuthResponse
	(*ChallengeRequest)(nil),        // 17: sakissh.ChallengeRequest
	(*ChallengeResponse)(nil),       // 18: sakissh.ChallengeResponse
	(*SecurityStatusRequest)(nil),   // 19: sakissh.SecurityStatusRequest
	(*SecurityStatusResponse)(nil),  // 20: sakissh.SecurityStatusResponse
	(*RawFileChunk)(nil),            // 21: sakissh.RawFileChunk
	(*RawFileMetadata)(nil),         // 22: sakissh.RawFileMetadata
	(*RawFileTransferResponse)(nil), // 23: sakissh.RawFileTransferResponse
	(*RenewSessionRequest)(nil),     // 24: sakissh.RenewSessionRequest
	(*RenewSessionResponse)(nil),    // 25: sakissh.RenewSessionResponse
	nil,                             // 26: sakissh.ExecuteRequest.EnvEntry
}
var file_sakissh_proto_depIdxs = []int32{
	26, // 0: sakissh.ExecuteRequest.env:type_name -> sakissh.ExecuteRequest.EnvEntry
	1,  // 1: sakissh.StreamResponse.source:type_name -> sakissh.StreamResponse.Source
	0,  // 2: sakissh.SignalRequest.signal:type_name -> sakissh.PosixSignal
	12, // 3: sakissh.FileChunk.metadata:type_name -> sakissh.FileMetadata
	22, // 4: sakissh.RawFileChunk.metadata:type_name -> sakissh.RawFileMetadata
	2,  // 5: sakissh.SakiSSH.Execute:input_type -> sakissh.ExecuteRequest
	2,  // 6: sakissh.SakiSSH.ExecuteStream:input_type -> sakissh.ExecuteRequest
	5,  // 7: sakissh.SakiSSH.Cancel:input_type -> sakissh.CancelRequest
	7,  // 8: sakissh.SakiSSH.Signal:input_type -> sakissh.SignalRequest
	9,  // 9: sakissh.SakiSSH.Ping:input_type -> sakissh.PingRequest
	11, // 10: sakissh.SakiSSH.FileUpload:input_type -> sakissh.FileChunk
	14, // 11: sakissh.SakiSSH.FileDownload:input_type -> sakissh.FileDownloadRequest
	15, // 12: sakissh.SakiSSH.Authenticate:input_type -> sakissh.AuthRequest
	17, // 13: sakissh.SakiSSH.CognitiveChallenge:input_type -> sakissh.ChallengeRequest
	19, // 14: sakissh.SakiSSH.SecurityStatus:input_type -> sakissh.SecurityStatusRequest
	21, // 15: sakissh.SakiSSH.RawFileTransfer:input_type -> sakissh.RawFileChunk
	24, // 16: sakissh.SakiSSH.RenewSession:input_type -> sakissh.RenewSessionRequest
	3,  // 17: sakissh.SakiSSH.Execute:output_type -> sakissh.ExecuteResponse
	4,  // 18: sakissh.SakiSSH.ExecuteStream:output_type -> sakissh.StreamResponse
	6,  // 19: sakissh.SakiSSH.Cancel:output_type -> sakissh.CancelResponse
	8,  // 20: sakissh.SakiSSH.Signal:output_type -> sakissh.SignalResponse
	10, // 21: sakissh.SakiSSH.Ping:output_type -> sakissh.PingResponse
	13, // 22: sakissh.SakiSSH.FileUpload:output_type -> sakissh.FileTransferResponse
	11, // 23: sakissh.SakiSSH.FileDownload:output_type -> sakissh.FileChunk
	16, // 24: sakissh.SakiSSH.Authenticate:output_type -> sakissh.AuthResponse
	18, // 25: sakissh.SakiSSH.CognitiveChallenge:output_type -> sakissh.ChallengeResponse
	20, // 26: sakissh.SakiSSH.SecurityStatus:output_type -> sakissh.SecurityStatusResponse
	23, // 27: sakissh.SakiSSH.RawFileTransfer:output_type -> sakissh.RawFileTransferResponse
	25, // 28: sakissh.SakiSSH.RenewSession:output_type -> sakissh.RenewSessionResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sakissh_proto_init() }
func file_sakissh_proto_init() {
	if File_sakissh_proto != nil {
		return
	}
	file_sakissh_proto_msgTypes[2].OneofWrappers = []any{}
	file_sakissh_proto_msgTypes[9].OneofWrappers = []any{
		(*FileChunk_Metadata)(nil),
		(*FileChunk_Data)(nil),
	}
	file_sakissh_proto_msgTypes[19].OneofWrappers = []any{
		(*RawFileChunk_Metadata)(nil),
		(*RawFileChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sakissh_proto_rawDesc), len(file_sakissh_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sakissh_proto_goTypes,
		DependencyIndexes: file_sakissh_proto_depIdxs,
		EnumInfos:         file_sakissh_proto_enumTypes,
		MessageInfos:      file_sakissh_proto_msgTypes,
	}.Build()
	File_sakissh_proto = out.File
	file_sakissh_proto_goTypes = nil
	file_sakissh_proto_depIdxs = nil
}
