// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.35.0
// source: sakissh.proto

package sakissh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SakiSSHClient is the client API for SakiSSH service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SakiSSHClient interface {
	// 執行指令並返回單次結果 (用於快速指令)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// 流式執行指令 (用於需要實時輸出或互動的場景)
	ExecuteStream(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (SakiSSH_ExecuteStreamClient, error)
	// 取消執行中的進程 (無 timeout，取消即殺)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// 對執行中的進程發送 POSIX 信號
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	// 連線狀態自檢 (Client 單向 request)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// 檔案上傳 (Client → Daemon 串流)
	FileUpload(ctx context.Context, opts ...grpc.CallOption) (SakiSSH_FileUploadClient, error)
	// 檔案下載 (Daemon → Client 串流)
	FileDownload(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (SakiSSH_FileDownloadClient, error)
	// 原始二進位檔案直寫 (Network layer to OS write)，避開 CJK 轉譯
	RawFileTransfer(ctx context.Context, opts ...grpc.CallOption) (SakiSSH_RawFileTransferClient, error)
	// SSH 風格認證 (ED25519 challenge-response)
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// 查詢當前 session 的 capability set
	GetCapabilities(ctx context.Context, in *CapabilityRequest, opts ...grpc.CallOption) (*CapabilityResponse, error)
	// 續約 session（延長 expires_at）
	RenewSession(ctx context.Context, in *SessionRenewRequest, opts ...grpc.CallOption) (*SessionRenewResponse, error)
	// ChaCha20 認知挑戰 — 驗證 Agent 是否具備真實計算能力
	ChaChaCognitiveChallenge(ctx context.Context, in *CognitiveChallengeRequest, opts ...grpc.CallOption) (*CognitiveChallengeResponse, error)
	// 查詢 Daemon 的 TLS 與安全配置狀態
	GetSecurityStatus(ctx context.Context, in *SecurityStatusRequest, opts ...grpc.CallOption) (*SecurityStatusResponse, error)
	// ============================================================
	// v6.0 新增：WASM 動態沙盒與算力卸載
	// ============================================================
	ExecuteWasm(ctx context.Context, in *WasmRequest, opts ...grpc.CallOption) (SakiSSH_ExecuteWasmClient, error)
	// ============================================================
	// Phase 9 新增：密碼學稽核金鑰廣播
	// ============================================================
	// 取得 Daemon 端的 Ed25519 稽核公鑰 (供外部驗證日誌鏈)
	GetAuditPublicKey(ctx context.Context, in *GetAuditPublicKeyRequest, opts ...grpc.CallOption) (*GetAuditPublicKeyResponse, error)
}

type sakiSSHClient struct {
	cc grpc.ClientConnInterface
}

func NewSakiSSHClient(cc grpc.ClientConnInterface) SakiSSHClient {
	return &sakiSSHClient{cc}
}

func (c *sakiSSHClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/sakissh.SakiSSH/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) ExecuteStream(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (SakiSSH_ExecuteStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &SakiSSH_ServiceDesc.Streams[0], "/sakissh.SakiSSH/ExecuteStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &sakiSSHExecuteStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SakiSSH_ExecuteStreamClient interface {
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type sakiSSHExecuteStreamClient struct {
	grpc.ClientStream
}

func (x *sakiSSHExecuteStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sakiSSHClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, "/sakissh.SakiSSH/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, "/sakissh.SakiSSH/Signal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/sakissh.SakiSSH/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) FileUpload(ctx context.Context, opts ...grpc.CallOption) (SakiSSH_FileUploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &SakiSSH_ServiceDesc.Streams[1], "/sakissh.SakiSSH/FileUpload", opts...)
	if err != nil {
		return nil, err
	}
	x := &sakiSSHFileUploadClient{stream}
	return x, nil
}

type SakiSSH_FileUploadClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*FileTransferResponse, error)
	grpc.ClientStream
}

type sakiSSHFileUploadClient struct {
	grpc.ClientStream
}

func (x *sakiSSHFileUploadClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sakiSSHFileUploadClient) CloseAndRecv() (*FileTransferResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileTransferResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sakiSSHClient) FileDownload(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (SakiSSH_FileDownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &SakiSSH_ServiceDesc.Streams[2], "/sakissh.SakiSSH/FileDownload", opts...)
	if err != nil {
		return nil, err
	}
	x := &sakiSSHFileDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SakiSSH_FileDownloadClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type sakiSSHFileDownloadClient struct {
	grpc.ClientStream
}

func (x *sakiSSHFileDownloadClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sakiSSHClient) RawFileTransfer(ctx context.Context, opts ...grpc.CallOption) (SakiSSH_RawFileTransferClient, error) {
	stream, err := c.cc.NewStream(ctx, &SakiSSH_ServiceDesc.Streams[3], "/sakissh.SakiSSH/RawFileTransfer", opts...)
	if err != nil {
		return nil, err
	}
	x := &sakiSSHRawFileTransferClient{stream}
	return x, nil
}

type SakiSSH_RawFileTransferClient interface {
	Send(*RawFileChunk) error
	CloseAndRecv() (*RawFileTransferResponse, error)
	grpc.ClientStream
}

type sakiSSHRawFileTransferClient struct {
	grpc.ClientStream
}

func (x *sakiSSHRawFileTransferClient) Send(m *RawFileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sakiSSHRawFileTransferClient) CloseAndRecv() (*RawFileTransferResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RawFileTransferResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sakiSSHClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/sakissh.SakiSSH/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) GetCapabilities(ctx context.Context, in *CapabilityRequest, opts ...grpc.CallOption) (*CapabilityResponse, error) {
	out := new(CapabilityResponse)
	err := c.cc.Invoke(ctx, "/sakissh.SakiSSH/GetCapabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) RenewSession(ctx context.Context, in *SessionRenewRequest, opts ...grpc.CallOption) (*SessionRenewResponse, error) {
	out := new(SessionRenewResponse)
	err := c.cc.Invoke(ctx, "/sakissh.SakiSSH/RenewSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) ChaChaCognitiveChallenge(ctx context.Context, in *CognitiveChallengeRequest, opts ...grpc.CallOption) (*CognitiveChallengeResponse, error) {
	out := new(CognitiveChallengeResponse)
	err := c.cc.Invoke(ctx, "/sakissh.SakiSSH/ChaChaCognitiveChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) GetSecurityStatus(ctx context.Context, in *SecurityStatusRequest, opts ...grpc.CallOption) (*SecurityStatusResponse, error) {
	out := new(SecurityStatusResponse)
	err := c.cc.Invoke(ctx, "/sakissh.SakiSSH/GetSecurityStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sakiSSHClient) ExecuteWasm(ctx context.Context, in *WasmRequest, opts ...grpc.CallOption) (SakiSSH_ExecuteWasmClient, error) {
	stream, err := c.cc.NewStream(ctx, &SakiSSH_ServiceDesc.Streams[4], "/sakissh.SakiSSH/ExecuteWasm", opts...)
	if err != nil {
		return nil, err
	}
	x := &sakiSSHExecuteWasmClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SakiSSH_ExecuteWasmClient interface {
	Recv() (*WasmResponse, error)
	grpc.ClientStream
}

type sakiSSHExecuteWasmClient struct {
	grpc.ClientStream
}

func (x *sakiSSHExecuteWasmClient) Recv() (*WasmResponse, error) {
	m := new(WasmResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sakiSSHClient) GetAuditPublicKey(ctx context.Context, in *GetAuditPublicKeyRequest, opts ...grpc.CallOption) (*GetAuditPublicKeyResponse, error) {
	out := new(GetAuditPublicKeyResponse)
	err := c.cc.Invoke(ctx, "/sakissh.SakiSSH/GetAuditPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SakiSSHServer is the server API for SakiSSH service.
// All implementations must embed UnimplementedSakiSSHServer
// for forward compatibility
type SakiSSHServer interface {
	// 執行指令並返回單次結果 (用於快速指令)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// 流式執行指令 (用於需要實時輸出或互動的場景)
	ExecuteStream(*ExecuteRequest, SakiSSH_ExecuteStreamServer) error
	// 取消執行中的進程 (無 timeout，取消即殺)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	// 對執行中的進程發送 POSIX 信號
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	// 連線狀態自檢 (Client 單向 request)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// 檔案上傳 (Client → Daemon 串流)
	FileUpload(SakiSSH_FileUploadServer) error
	// 檔案下載 (Daemon → Client 串流)
	FileDownload(*FileDownloadRequest, SakiSSH_FileDownloadServer) error
	// 原始二進位檔案直寫 (Network layer to OS write)，避開 CJK 轉譯
	RawFileTransfer(SakiSSH_RawFileTransferServer) error
	// SSH 風格認證 (ED25519 challenge-response)
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	// 查詢當前 session 的 capability set
	GetCapabilities(context.Context, *CapabilityRequest) (*CapabilityResponse, error)
	// 續約 session（延長 expires_at）
	RenewSession(context.Context, *SessionRenewRequest) (*SessionRenewResponse, error)
	// ChaCha20 認知挑戰 — 驗證 Agent 是否具備真實計算能力
	ChaChaCognitiveChallenge(context.Context, *CognitiveChallengeRequest) (*CognitiveChallengeResponse, error)
	// 查詢 Daemon 的 TLS 與安全配置狀態
	GetSecurityStatus(context.Context, *SecurityStatusRequest) (*SecurityStatusResponse, error)
	// ============================================================
	// v6.0 新增：WASM 動態沙盒與算力卸載
	// ============================================================
	ExecuteWasm(*WasmRequest, SakiSSH_ExecuteWasmServer) error
	// ============================================================
	// Phase 9 新增：密碼學稽核金鑰廣播
	// ============================================================
	// 取得 Daemon 端的 Ed25519 稽核公鑰 (供外部驗證日誌鏈)
	GetAuditPublicKey(context.Context, *GetAuditPublicKeyRequest) (*GetAuditPublicKeyResponse, error)
	mustEmbedUnimplementedSakiSSHServer()
}

// UnimplementedSakiSSHServer must be embedded to have forward compatible implementations.
type UnimplementedSakiSSHServer struct {
}

func (UnimplementedSakiSSHServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedSakiSSHServer) ExecuteStream(*ExecuteRequest, SakiSSH_ExecuteStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteStream not implemented")
}
func (UnimplementedSakiSSHServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedSakiSSHServer) Signal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedSakiSSHServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSakiSSHServer) FileUpload(SakiSSH_FileUploadServer) error {
	return status.Errorf(codes.Unimplemented, "method FileUpload not implemented")
}
func (UnimplementedSakiSSHServer) FileDownload(*FileDownloadRequest, SakiSSH_FileDownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method FileDownload not implemented")
}
func (UnimplementedSakiSSHServer) RawFileTransfer(SakiSSH_RawFileTransferServer) error {
	return status.Errorf(codes.Unimplemented, "method RawFileTransfer not implemented")
}
func (UnimplementedSakiSSHServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedSakiSSHServer) GetCapabilities(context.Context, *CapabilityRequest) (*CapabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedSakiSSHServer) RenewSession(context.Context, *SessionRenewRequest) (*SessionRenewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewSession not implemented")
}
func (UnimplementedSakiSSHServer) ChaChaCognitiveChallenge(context.Context, *CognitiveChallengeRequest) (*CognitiveChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChaChaCognitiveChallenge not implemented")
}
func (UnimplementedSakiSSHServer) GetSecurityStatus(context.Context, *SecurityStatusRequest) (*SecurityStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecurityStatus not implemented")
}
func (UnimplementedSakiSSHServer) ExecuteWasm(*WasmRequest, SakiSSH_ExecuteWasmServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteWasm not implemented")
}
func (UnimplementedSakiSSHServer) GetAuditPublicKey(context.Context, *GetAuditPublicKeyRequest) (*GetAuditPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuditPublicKey not implemented")
}
func (UnimplementedSakiSSHServer) mustEmbedUnimplementedSakiSSHServer() {}

// UnsafeSakiSSHServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SakiSSHServer will
// result in compilation errors.
type UnsafeSakiSSHServer interface {
	mustEmbedUnimplementedSakiSSHServer()
}

func RegisterSakiSSHServer(s grpc.ServiceRegistrar, srv SakiSSHServer) {
	s.RegisterService(&SakiSSH_ServiceDesc, srv)
}

func _SakiSSH_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sakissh.SakiSSH/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_ExecuteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SakiSSHServer).ExecuteStream(m, &sakiSSHExecuteStreamServer{stream})
}

type SakiSSH_ExecuteStreamServer interface {
	Send(*StreamResponse) error
	grpc.ServerStream
}

type sakiSSHExecuteStreamServer struct {
	grpc.ServerStream
}

func (x *sakiSSHExecuteStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SakiSSH_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sakissh.SakiSSH/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sakissh.SakiSSH/Signal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).Signal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sakissh.SakiSSH/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_FileUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SakiSSHServer).FileUpload(&sakiSSHFileUploadServer{stream})
}

type SakiSSH_FileUploadServer interface {
	SendAndClose(*FileTransferResponse) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type sakiSSHFileUploadServer struct {
	grpc.ServerStream
}

func (x *sakiSSHFileUploadServer) SendAndClose(m *FileTransferResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sakiSSHFileUploadServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SakiSSH_FileDownload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SakiSSHServer).FileDownload(m, &sakiSSHFileDownloadServer{stream})
}

type SakiSSH_FileDownloadServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type sakiSSHFileDownloadServer struct {
	grpc.ServerStream
}

func (x *sakiSSHFileDownloadServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _SakiSSH_RawFileTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SakiSSHServer).RawFileTransfer(&sakiSSHRawFileTransferServer{stream})
}

type SakiSSH_RawFileTransferServer interface {
	SendAndClose(*RawFileTransferResponse) error
	Recv() (*RawFileChunk, error)
	grpc.ServerStream
}

type sakiSSHRawFileTransferServer struct {
	grpc.ServerStream
}

func (x *sakiSSHRawFileTransferServer) SendAndClose(m *RawFileTransferResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sakiSSHRawFileTransferServer) Recv() (*RawFileChunk, error) {
	m := new(RawFileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SakiSSH_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sakissh.SakiSSH/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sakissh.SakiSSH/GetCapabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).GetCapabilities(ctx, req.(*CapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_RenewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).RenewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sakissh.SakiSSH/RenewSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).RenewSession(ctx, req.(*SessionRenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_ChaChaCognitiveChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CognitiveChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).ChaChaCognitiveChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sakissh.SakiSSH/ChaChaCognitiveChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).ChaChaCognitiveChallenge(ctx, req.(*CognitiveChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_GetSecurityStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).GetSecurityStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sakissh.SakiSSH/GetSecurityStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).GetSecurityStatus(ctx, req.(*SecurityStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SakiSSH_ExecuteWasm_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WasmRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SakiSSHServer).ExecuteWasm(m, &sakiSSHExecuteWasmServer{stream})
}

type SakiSSH_ExecuteWasmServer interface {
	Send(*WasmResponse) error
	grpc.ServerStream
}

type sakiSSHExecuteWasmServer struct {
	grpc.ServerStream
}

func (x *sakiSSHExecuteWasmServer) Send(m *WasmResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SakiSSH_GetAuditPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SakiSSHServer).GetAuditPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sakissh.SakiSSH/GetAuditPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SakiSSHServer).GetAuditPublicKey(ctx, req.(*GetAuditPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SakiSSH_ServiceDesc is the grpc.ServiceDesc for SakiSSH service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SakiSSH_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sakissh.SakiSSH",
	HandlerType: (*SakiSSHServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _SakiSSH_Execute_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _SakiSSH_Cancel_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _SakiSSH_Signal_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _SakiSSH_Ping_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _SakiSSH_Authenticate_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _SakiSSH_GetCapabilities_Handler,
		},
		{
			MethodName: "RenewSession",
			Handler:    _SakiSSH_RenewSession_Handler,
		},
		{
			MethodName: "ChaChaCognitiveChallenge",
			Handler:    _SakiSSH_ChaChaCognitiveChallenge_Handler,
		},
		{
			MethodName: "GetSecurityStatus",
			Handler:    _SakiSSH_GetSecurityStatus_Handler,
		},
		{
			MethodName: "GetAuditPublicKey",
			Handler:    _SakiSSH_GetAuditPublicKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteStream",
			Handler:       _SakiSSH_ExecuteStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileUpload",
			Handler:       _SakiSSH_FileUpload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FileDownload",
			Handler:       _SakiSSH_FileDownload_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RawFileTransfer",
			Handler:       _SakiSSH_RawFileTransfer_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ExecuteWasm",
			Handler:       _SakiSSH_ExecuteWasm_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sakissh.proto",
}
